// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm28GXG8BT08V75z8U1awY-mG1nmYWXQc',
    appId: '1:177101534878:android:c29be51ceff58aaf4c6d8f',
    messagingSenderId: '177101534878',
    projectId: 'millima-app',
    storageBucket: 'millima-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVG3HKMVwHTyEgZSWoC9MxEQI0m-dWVB0',
    appId: '1:177101534878:ios:c757bf5a36b56bb24c6d8f',
    messagingSenderId: '177101534878',
    projectId: 'millima-app',
    storageBucket: 'millima-app.appspot.com',
    androidClientId: '177101534878-vfb7puh5f4nlh5omhehlbjqrsv7ok7s2.apps.googleusercontent.com',
    iosClientId: '177101534878-bu2fr7cr8k14p6v66ofhmggpr2ml1rn7.apps.googleusercontent.com',
    iosBundleId: 'uz.flutterwithakmaljon.millima',
  );

}